name: Build manylinx wheels and deploy

permissions:
  contents: write

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build Wheel
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx11abi: [ TRUE, FALSE ]
        include:
          # see https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix
          # Pytorch >= 2.2 support Python 3.12
          - torch-version: "2.2.2"
            python-version: "3.9"
            cuda-version: "12.1.1"
          - torch-version: "2.2.2"
            python-version: "3.10"
            cuda-version: "12.1.1"
          - torch-version: "2.2.2"
            python-version: "3.11"
            cuda-version: "12.1.1"
          - torch-version: "2.3.1"
            python-version: "3.9"
            cuda-version: "12.1.1"
          - torch-version: "2.3.1"
            python-version: "3.10"
            cuda-version: "12.1.1"
          - torch-version: "2.3.1"
            python-version: "3.11"
            cuda-version: "12.1.1"
          - torch-version: "2.4.1"
            python-version: "3.9"
            cuda-version: "12.1.1"
          - torch-version: "2.4.1"
            python-version: "3.9"
            cuda-version: "12.4.0"
          - torch-version: "2.4.1"
            python-version: "3.10"
            cuda-version: "12.1.1"
          - torch-version: "2.4.1"
            python-version: "3.10"
            cuda-version: "12.4.0"
          - torch-version: "2.4.1"
            python-version: "3.11"
            cuda-version: "12.1.1"
          - torch-version: "2.4.1"
            python-version: "3.11"
            cuda-version: "12.4.0"
          - torch-version: "2.5.1"
            python-version: "3.9"
            cuda-version: "12.1.1"
          - torch-version: "2.5.1"
            python-version: "3.9"
            cuda-version: "12.4.0"
          - torch-version: "2.5.1"
            python-version: "3.10"
            cuda-version: "12.1.1"
          - torch-version: "2.5.1"
            python-version: "3.10"
            cuda-version: "12.4.0"
          - torch-version: "2.5.1"
            python-version: "3.11"
            cuda-version: "12.1.1"
          - torch-version: "2.5.1"
            python-version: "3.11"
            cuda-version: "12.4.0"
          - torch-version: "2.5.1"
            python-version: "3.12"
            cuda-version: "12.1.1"
          - torch-version: "2.5.1"
            python-version: "3.12"
            cuda-version: "12.4.0"
          - torch-version: "2.6.0"
            python-version: "3.9"
            cuda-version: "12.4.0"
          - torch-version: "2.6.0"
            python-version: "3.9"
            cuda-version: "12.6.0"
          - torch-version: "2.6.0"
            python-version: "3.10"
            cuda-version: "12.4.0"
          - torch-version: "2.6.0"
            python-version: "3.10"
            cuda-version: "12.6.0"
          - torch-version: "2.6.0"
            python-version: "3.11"
            cuda-version: "12.4.0"
          - torch-version: "2.6.0"
            python-version: "3.11"
            cuda-version: "12.6.0"
          - torch-version: "2.6.0"
            python-version: "3.12"
            cuda-version: "12.4.0"
          - torch-version: "2.6.0"
            python-version: "3.12"
            cuda-version: "12.6.0"

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout TransformerEngine
        uses: actions/checkout@v4
        with:
          repository: NVIDIA/TransformerEngine
          submodules: recursive
          ref: v2.0

      - name: Checkout utils
        uses: actions/checkout@v4
        with:
          path: build_scripts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set CUDA and PyTorch versions ${{ matrix.torch-version }}+cu${{ matrix.cuda-version }}
        run: |
          echo "CI_CUDA_VERSION=$(echo ${{ matrix.cuda-version }})" >> $GITHUB_ENV
          echo "CI_TORCH_VERSION=$(echo ${{ matrix.torch-version }})" >> $GITHUB_ENV
          echo "CI_PYTHON_VERSION=$(echo ${{ matrix.python-version }})" >> $GITHUB_ENV
          echo "MATRIX_CUDA_VERSION=$(echo ${{ matrix.cuda-version }} | awk -F \. {'print $1 $2'})" >> $GITHUB_ENV
          echo "MATRIX_TORCH_VERSION=$(echo ${{ matrix.torch-version }} | awk -F \. {'print $1 "." $2'})" >> $GITHUB_ENV
          echo "MATRIX_PYTHON_VERSION=$(echo ${{ matrix.python-version }} | awk -F \. {'print $1 $2'})" >> $GITHUB_ENV

      - name: Install cibuildwheel
        run: |
          echo "MANYLINUX_CUDA_VERSION=$(python -c "from os import environ as env; print({'118': '11.8', '121': '12.1', '124': '12.4', '126': '12.6'}[env['MATRIX_CUDA_VERSION']])")" >> $GITHUB_ENV
          echo "MANYLINUX_NVTX_CUDA_VERSION=$(python -c "from os import environ as env; print({'118': '11-8', '121': '12-1', '124': '12-4', '126': '12-6'}[env['MATRIX_CUDA_VERSION']])")" >> $GITHUB_ENV
          echo "MANYLINUX_CUDNN_CUDA_VERSION=$(echo ${{ matrix.cuda-version }} | awk -F \. {'print $1'})" >> $GITHUB_ENV
          python3 -m pip install --upgrade pip
          python3 -m pip install cibuildwheel

      - name: Build wheels for Pytorch ${{ matrix.torch-version }}+cu${{ matrix.cuda-version }}
        run: |
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: cp${{ env.MATRIX_PYTHON_VERSION }}-*64
          CIBW_MANYLINUX_X86_64_IMAGE: pytorch/manylinux2_28-builder:cuda${{ env.MANYLINUX_CUDA_VERSION }}
          CIBW_BEFORE_BUILD_LINUX: >
            bash build_scripts/prepare_for_build.sh
          CIBW_ENVIRONMENT: CUDA_HOME="/usr/local/cuda-${{ env.MANYLINUX_CUDA_VERSION }}" CUDACXX="/usr/local/cuda-${{ env.MANYLINUX_CUDA_VERSION }}/bin/nvcc" CFLAGS="-I/usr/include" LDFLAGS="-L/usr/lib" NVTE_NO_LOCAL_VERSION=1 AUDITWHEEL_PLAT="manylinux_2_28_$(uname -m)" MATRIX_CUDA_VERSION=${{ env.MATRIX_CUDA_VERSION }} MATRIX_TORCH_VERSION=${{ env.MATRIX_TORCH_VERSION }} MATRIX_PYTHON_VERSION=${{ env.MATRIX_PYTHON_VERSION }} CI_CUDA_VERSION=${{ env.CI_CUDA_VERSION }} CI_TORCH_VERSION=${{ env.CI_TORCH_VERSION }} CI_PYTHON_VERSION=${{ env.CI_PYTHON_VERSION }} CXX11_ABI=${{ matrix.cxx11abi }} NVTE_FRAMEWORK=pytorch MAX_JOBS=1 NVTE_BUILD_THREADS_PER_JOB=1
          CIBW_SKIP: "*musllinux*"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair -w /tmp/cibuildwheel/repaired_wheel {wheel} --exclude libc10.so --exclude libc10_cuda.so --exclude libtorch.so --exclude libtorch_python.so --exclude libtorch_cpu.so --exclude libtorch_cuda.so --exclude libtorch_cuda_cpp.so --exclude libtorch_cuda_cu.so --exclude libcuda.so.1 --exclude libcufile.so.0 --exclude libcufile.so --exclude libcudart.so.12 --exclude libcudart.so.11.0 --exclude libcudart.so.11 --exclude libnccl.so --exclude libnccl.so.1 --exclude libnccl.so.2 --exclude libcudart.so.11 --exclude libcudart.so.12 --exclude libcudart.so.11.0 --exclude libcudart.so.12.0 --exclude libcurand.so.10 --exclude libcublas.so.12 --exclude libcublasLt.so.12"

      - name: Log Built Wheels
        run: |
          wheel_name=$(ls dist/*whl | xargs -n 1 basename)
          echo "wheel_name=${wheel_name}" >> $GITHUB_ENV
          ls dist

      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.wheel_name}}
          path: dist/${{env.wheel_name}}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/${{env.wheel_name}}
